language: node_js
node_js:
- '8'
deploy:
  - provider: npm
    email: code@oledid.com
    skip_cleanup: true
    api_key:
      secure: m9krh2MC4qvwX0ZE7RyvIkBnHlUe+KDMbKLiIUqTv/Wh3v1kE+jEBnEAai0rzszQA859aGyNDTmcU8DHSj+eI6nkBJCn8+Tegp0RXOj3mOzQf4AhwVnCEGTiEF387+YHBu7B2MbSfL6b68O4E1luuTBlok+WrUKZewxnUESrkSjkF/oaamOX7y9/ssiC0nCsaWPC/FI4HRLDMqJK+lS4A1uEYcnssAqQf7UPd/ZNtHQiFuJhTCz7sA4fsBKqYCCgYIZOZsclaTQlZeZwhEcBMdjwTVPX9VPEwJD6xideG7E0ko2v/ECCpv8eFxgnIP2L1+Uif73NBAkpgWVn8i/3exs0oNG/QHgCeOn0Gs05nP+oorxLOWIRBcJj4srOw9sRs2FCYUdWamdRTDC7a5S/RCuQ5uMks4W91zBM5+QeTj3tcgm11jGBnStDGMc3h+uqBb+XhL0GgeQc7qOz+KbQB9S67IVH49VDHcy9ITgHKcgHtnmUgQftx3p8b6Mu85+H2nKbokgf5KiTCdw//k0q/bovLZlgaXJMtavzMbVBWnCcVnJ26Zu2FUB1ngFCtAM8ZXK74/CSAmbc8fvzYn2kNlE9OIHzs4DF6xhnWUpHmcodHsGRSU30V1RrrZv5R7+RLz69bWXmjyKCtYwRWkZkDEqCdPAE4+tfqhVeA4eU9zs=
    on:
      tags: true
  - provider: releases
    api_key:
      secure: i8jjAQhATnbB9UdzvK1rK0Fo0CTkKRrNvG3FegUo+gH7pfjiuGUBvotbCN5ltDOj+0G1/LcRExLGmHa+Qu1WHr6aXY/oSHJ3vSKwEeFa3sNKTkqlYq66BC6tsnB2FZcBF24KdWnuZvz4dCOTRLWuLHoqJt3r2B012OgucLqlDXf1NtTCOkUPb7a9OGuQu0yt9ceOLNEJQaTTbKpUE1w1czBkfZgJOtLmt6ybKX6JO9fadmi53zlhyxluXkVpm4CGozyXnBmSO4OO0zbs5WXchcmJXeBM8YEwtKBhJpU8d23wjQFy6aK+LUrPJG5otwe7yu6+wmgY8dXCJkFPOcqE5DXwmuxQNSC+js5qoVpyVEk2dZOdhk+7f61LI5roa3uMQVblYnljN8Ilm8r92vOu/XIVBnRaRwpUJKIwQfjd2k0tu2CEULFEqsxNfzckR1mhbB2ffdPNlbzAWYZrRI/EGzsQ7fSitVbjo9oAGmVNoYEVAdCZ46XVKXet6dKRy8buJ8pwfGpHTPOhonWPeLr19AQ8zwf3B6h8rukyQaBlFcT1vLQZMAYzbqihdVkIrbuw+sAbC3e0hZs4WrOjBOoUFISuV10OaJcVb7N741+ucLjIYYY7rHXhV7y/0fzl+63a4YLyFVO9w7zMJOM6xeKJuXvhaCePfK9eoj+xhMgUmXA=
    skip_cleanup: true
    on:
      tags: true
